import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { Toaster } from "react-hot-toast";
import { ErrorBoundary } from "~/app/_components/error_boundary";
import { AuthProvider } from "~/contexts/auth-context";

export const metadata: Metadata = {
  title: 'T3-Clone',
  description: 'Generated by create next app',
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} antialiased`} data-cursorstyle="true" data-effect-ective="true">
      <body>
        <ErrorBoundary>
          <TRPCReactProvider>
            <AuthProvider>
              <Toaster position="bottom-center" />
              {children}
            </AuthProvider>
          </TRPCReactProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}